/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.myled;
//import it.unibo.bls.raspberry.components.adhoc.DeviceLedPi4jAdHoc;
import it.unibo.myled.LedWithGui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Myled extends AbstractMyled { 
	
	private   LedWithRasp ledPi4j ;

	private LedWithGui    ledGui ;
	private boolean withGui = false ;
	
	public Myled(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void createGuiLed(int pinNum ){
		withGui = true;
		ledGui = new LedWithGui(  );		
		outEnvView.getEnv().addPanel(ledGui);
	}
	
	public void createPi4jLed(int pinNum ){
		ledPi4j = new LedWithRasp(pinNum);
	}
	
	public void switchLedState(){
		if (!withGui){
			ledPi4j.ledSwitch();
			System.out.println("LED is " + (ledPi4j.isOn()?"ON":"OFF"));
		}
		else {
			ledGui.ledSwitch();
		}
	}
}
