/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.mybutton;
import java.awt.Button;

import it.unibo.mybutton.ButtonListener;
//import it.unibo.bls.raspberry.components.adhoc.DeviceButtonPi4JAdHoc;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
public class Mybutton extends AbstractMybutton{ 
	
	
	private ButtonListener btnListener ;  
	private Button btnGui ;
	
	public Mybutton(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	
	public void createGuiButton(int pinNum ){
		btnGui      = new Button("CLICK");
		btnListener = new ButtonListener(this);
		btnGui.addActionListener( btnListener );
		outEnvView.getEnv().addPanel(btnGui);
	}
	
	/*
	public void createPi4jButton(int pinNum){
		try {
			DeviceButtonPi4JAdHoc buttonPi4j  = new DeviceButtonPi4JAdHoc(  outEnvView , pinNum);
			buttonPi4j.addObserver(this);
		} catch (Exception e) {
 			e.printStackTrace();
		}
	}
	*/
		
	public void controlLogic(String cmd){
		try {
			sendMsg("click", "myled", QActorContext.dispatch,"click(1)");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}		
	}
}
