/* Generated by AN DISI Unibo */ 
package it.unibo.ctxLed;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxLed  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxled", "./srcMore/it/unibo/ctxLed/blsdistributed.pl", 
		"./srcMore/it/unibo/ctxLed/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
   		//if( ctx.getEnv() == null){ ctx.terminateQActorSystem(); }
} 	
}
